class Character {
  constructor(name) {
    this._id = null;
    this._name = name;
    this._description = null;
    this._imgPathUrl = null;
    this._id_user = null;
  }
    static fromMap(map){
      let character = new Character(map.name);
      character._id = map.id;
      character._name = map.name;
      character._description = map.description;
      character._imgPathUrl = map.imgPathUrl;
      character._id_user = map.id_user;

      return character;
    }

    toMap(){
      return {
        id: this._id,
        name: this._name,
        description: this._description,
        imgPathUrl: this._imgPathUrl,
        id_user: this._id_user
      }
    }

    generateDescription(){
      //Generate with openai
      this._description = "Description generated with openai" + this.name + ", generated by openai for character";
    }
}
module.exports = Character;