class Discussion {
    constructor() {
      this.id = null;
      this.name = null;
      this.description = null;
      this.imgUrl = null;
      this.id_personnage = null;
      this.id_user = null;
    }
    static fromMap(map){
      let discussion = new Discussion();
      discussion.name = map.name;
      discussion.description = map.description;
      discussion.imgUrl = map.imgUrl;
      discussion.id_personnage = map.id_personnage;
      discussion.id_user = map.id_user;
        
      return discussion;
    }

    toMap(){
      return {
        id: this.id,
        name: this.name,
        description: this.description,
        imgUrl: this.imgUrl,
        id_personnage: this.id_personnage,
        id_user: this.id_user
      }
    }

    generateDescription(){
      //Generate with openai
      this.description = "Description generated with openai" + this.name + ", generated by openai";
    }
  }
  
  module.exports = Discussion;